name: Create Release file by newest tag

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set output
        id: vars
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
      - name: Check output
        env:
          TAG_NAME: ${{ steps.vars.outputs.tag }}
        run: |
          echo $TAG_NAME
          echo ${{ steps.vars.outputs.tag }}
    steps:
      - name: Build StatisticsAnalysisTool application
        run: |
            dotnet publish -c Release -p:Platform=x64 -p:PublishDir=bin\Release\net6.0-windows\publish\win-x64\ -p:PublishProtocol=FileSystem -p:TargetFramework=net6.0-windows -p:RuntimeIdentifier=win-x64 -p:SelfContained=false -p:PublishSingleFile=true -p:PublishReadyToRun=false
      - name: Create release archive
        run: |
            7z a -tzip StatisticsAnalysis-AlbionOnline-${{ env.TAG_NAME }}-x64.zip bin\Release\net6.0-windows\publish\win-x64\*